package ir.university.toosi.tms.view.basicinfo;


import com.fasterxml.jackson.databind.ObjectMapper;
import ir.university.toosi.tms.model.entity.BLookup;
import ir.university.toosi.tms.model.entity.Lookup;
import ir.university.toosi.tms.model.entity.WebServiceInfo;
import ir.university.toosi.tms.util.RESTfulClientUtil;
import ir.university.toosi.tms.util.ThreadPoolManager;

import javax.swing.*;
import java.io.IOException;

public class BLookupForm extends JInternalFrame {

    /**
     * Creates new form ContactEditor
     */

    public BLookupForm(boolean editMode, BLookup blookup, Lookup lookup, BasicInfoManagement basicInfoManagement) {
        this.editMode = editMode;
        this.bLookup = blookup;
        this.lookup = lookup;
        this.basicInfoManagement = basicInfoManagement;
        mainPanel = new JPanel();
        nameLabel = new JLabel();
        nameField = new JTextField();
        codeLabel = new JLabel();
        codeField = new JTextField();
        descLabel = new JLabel();
        descField = new JTextField();
        cancel = new JButton();
        ok = new JButton();
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.addInternalFrameListener(ThreadPoolManager.mainForm);
        setClosable(true);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOOKUP");

        mainPanel.setBorder(BorderFactory.createTitledBorder("BLOOKUP"));

        codeLabel.setText("CODE");

        if (editMode)
            codeField.setText(bLookup.getCode());
        else
            codeField.setText("");

        nameLabel.setText("NAME");

        if (editMode)
            nameField.setText(bLookup.getName());
        else
            nameField.setText("");

        descLabel.setText("DESC");

        if (editMode)
            descField.setText(bLookup.getDescription());
        else
            descField.setText("");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(codeLabel)
                                        .add(nameLabel)
                                        .add(descLabel))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, descField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, codeField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .add(nameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(codeLabel)
                                        .add(codeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(nameLabel)
                                        .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(descField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(descLabel))
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               close(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (editMode)
                    edit(evt);
                else
                    add(evt);
            }
        });


        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(120, Short.MAX_VALUE)
                                .add(ok)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cancel)
                                .add(104, 104, 104))
        );

        layout.linkSize(new java.awt.Component[]{cancel, ok}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(cancel)
                                        .add(ok))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.getAccessibleContext().setAccessibleName("BLookup");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add(java.awt.event.ActionEvent evt) {

        BLookup bLookup1 = new BLookup();
        bLookup1.setName(nameField.getText());
        bLookup1.setCode(codeField.getText());
        bLookup1.setDescription(descField.getText());
        bLookup1.setLookup(lookup);

        blookupService.setServiceName("/createBLookup");

        try {
            new ObjectMapper().readValue(new RESTfulClientUtil().restFullService(blookupService.getServerUrl(), blookupService.getServiceName(), new ObjectMapper().writeValueAsString(bLookup1)), BLookup.class);
        } catch (IOException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
        this.dispose();
        try {
            basicInfoManagement.refresh();
        } catch (IOException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
    }

    private void edit(java.awt.event.ActionEvent evt) {

        bLookup.setName(nameField.getText());
        bLookup.setCode(codeField.getText());
        bLookup.setDescription(descField.getText());
        bLookup.setLookup(lookup);

        blookupService.setServiceName("/editBLookup");

        try {
            new ObjectMapper().readValue(new RESTfulClientUtil().restFullService(blookupService.getServerUrl(), blookupService.getServiceName(), new ObjectMapper().writeValueAsString(bLookup)), Boolean.class);
        } catch (IOException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }

        this.dispose();
        try {
            basicInfoManagement.refresh();
        } catch (IOException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
    }

    private void close(java.awt.event.ActionEvent evt) {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancel;
    private JButton ok;
    private JLabel codeLabel;
    private JLabel nameLabel;
    private JLabel descLabel;
    private JPanel mainPanel;
    private JTextField codeField;
    private JTextField nameField;
    private JTextField descField;

    private boolean editMode;
    private BLookup bLookup;
    private Lookup lookup;
    private BasicInfoManagement basicInfoManagement;
    private WebServiceInfo blookupService = new WebServiceInfo();
    // End of variables declaration//GEN-END:variables

}
